// SPDX-License-Identifier: MIT
pragma solidity ^0.8.19;

/**
 * @title ZKSlashingVerifier
 * @notice Verifies zero-knowledge proofs for slashing evidence
 * @dev Uses Groth16 proofs generated by Circom circuits
 * 
 * This contract allows permissionless verification of validator offenses,
 * eliminating the need for validator voting on slashing decisions.
 */
contract ZKSlashingVerifier {
    
    // ============ Errors ============
    
    error InvalidProof();
    error ProofAlreadyUsed(bytes32 nullifier);
    error InvalidVerifyingKey();
    error UnauthorizedKeyUpdate();
    
    // ============ Types ============
    
    /// @notice Groth16 proof structure
    struct Proof {
        uint256[2] a;
        uint256[2][2] b;
        uint256[2] c;
    }
    
    /// @notice Types of slashing evidence
    enum EvidenceType {
        DoubleSign,      // Conflicting votes on same package
        FalseApproval,   // Approved malicious package
        Griefing         // Consistently voting against majority
    }
    
    /// @notice Verifying key for a proof type
    struct VerifyingKey {
        uint256[2] alpha1;
        uint256[2][2] beta2;
        uint256[2][2] gamma2;
        uint256[2][2] delta2;
        uint256[2][] ic;
    }
    
    // ============ State ============
    
    /// @notice Owner who can update verifying keys
    address public owner;
    
    /// @notice Used nullifiers to prevent replay attacks
    mapping(bytes32 => bool) public usedNullifiers;
    
    /// @notice Verifying keys for each evidence type
    mapping(EvidenceType => VerifyingKey) internal verifyingKeys;
    
    /// @notice Number of public inputs expected for each type
    mapping(EvidenceType => uint256) public publicInputCounts;
    
    /// @notice Total proofs verified
    uint256 public totalProofsVerified;
    
    // ============ Events ============
    
    event ProofVerified(
        EvidenceType indexed evidenceType,
        bytes32 indexed nullifier,
        address indexed verifier
    );
    
    event VerifyingKeyUpdated(
        EvidenceType indexed evidenceType,
        address indexed updater
    );
    
    event OwnershipTransferred(
        address indexed previousOwner,
        address indexed newOwner
    );
    
    // ============ Modifiers ============
    
    modifier onlyOwner() {
        require(msg.sender == owner, "Not owner");
        _;
    }
    
    // ============ Constructor ============
    
    constructor() {
        owner = msg.sender;
        
        // Initialize public input counts
        publicInputCounts[EvidenceType.DoubleSign] = 5;
        publicInputCounts[EvidenceType.FalseApproval] = 4;
        publicInputCounts[EvidenceType.Griefing] = 3;
    }
    
    // ============ External Functions ============
    
    /**
     * @notice Verify a double-sign proof
     * @param proof Groth16 proof
     * @param publicInputs [validatorPubkeyX, validatorPubkeyY, packageHash, vote1Hash, vote2Hash]
     * @return valid Whether proof is valid
     * @return nullifier Unique nullifier for this proof
     */
    function verifyDoubleSign(
        Proof calldata proof,
        uint256[5] calldata publicInputs
    ) external returns (bool valid, bytes32 nullifier) {
        // Compute nullifier
        nullifier = keccak256(abi.encodePacked(publicInputs));
        
        // Check not already used
        if (usedNullifiers[nullifier]) {
            revert ProofAlreadyUsed(nullifier);
        }
        
        // Build input array for verification
        uint256[] memory inputs = new uint256[](5);
        for (uint256 i = 0; i < 5; i++) {
            inputs[i] = publicInputs[i];
        }
        
        // Verify proof
        valid = _verifyProof(EvidenceType.DoubleSign, proof, inputs);
        
        if (!valid) {
            revert InvalidProof();
        }
        
        // Mark nullifier as used
        usedNullifiers[nullifier] = true;
        totalProofsVerified++;
        
        emit ProofVerified(EvidenceType.DoubleSign, nullifier, msg.sender);
        
        return (valid, nullifier);
    }
    
    /**
     * @notice Verify a false approval proof
     * @param proof Groth16 proof
     * @param publicInputs [validatorPubkey, packageHash, approvalTimestamp, revocationTimestamp]
     * @return valid Whether proof is valid
     * @return nullifier Unique nullifier for this proof
     */
    function verifyFalseApproval(
        Proof calldata proof,
        uint256[4] calldata publicInputs
    ) external returns (bool valid, bytes32 nullifier) {
        nullifier = keccak256(abi.encodePacked(publicInputs));
        
        if (usedNullifiers[nullifier]) {
            revert ProofAlreadyUsed(nullifier);
        }
        
        uint256[] memory inputs = new uint256[](4);
        for (uint256 i = 0; i < 4; i++) {
            inputs[i] = publicInputs[i];
        }
        
        valid = _verifyProof(EvidenceType.FalseApproval, proof, inputs);
        
        if (!valid) revert InvalidProof();
        
        usedNullifiers[nullifier] = true;
        totalProofsVerified++;
        
        emit ProofVerified(EvidenceType.FalseApproval, nullifier, msg.sender);
        
        return (valid, nullifier);
    }
    
    /**
     * @notice Verify a griefing proof
     * @param proof Groth16 proof
     * @param publicInputs [validatorPubkey, voteHistoryHash, disagreementRate]
     * @return valid Whether proof is valid
     * @return nullifier Unique nullifier for this proof
     */
    function verifyGriefing(
        Proof calldata proof,
        uint256[3] calldata publicInputs
    ) external returns (bool valid, bytes32 nullifier) {
        nullifier = keccak256(abi.encodePacked(publicInputs));
        
        if (usedNullifiers[nullifier]) {
            revert ProofAlreadyUsed(nullifier);
        }
        
        uint256[] memory inputs = new uint256[](3);
        for (uint256 i = 0; i < 3; i++) {
            inputs[i] = publicInputs[i];
        }
        
        valid = _verifyProof(EvidenceType.Griefing, proof, inputs);
        
        if (!valid) revert InvalidProof();
        
        usedNullifiers[nullifier] = true;
        totalProofsVerified++;
        
        emit ProofVerified(EvidenceType.Griefing, nullifier, msg.sender);
        
        return (valid, nullifier);
    }
    
    /**
     * @notice Set the verifying key for an evidence type
     * @param evidenceType Type of evidence
     * @param vk Verifying key
     */
    function setVerifyingKey(
        EvidenceType evidenceType,
        VerifyingKey calldata vk
    ) external onlyOwner {
        if (vk.ic.length == 0) revert InvalidVerifyingKey();
        
        verifyingKeys[evidenceType] = vk;
        
        emit VerifyingKeyUpdated(evidenceType, msg.sender);
    }
    
    /**
     * @notice Transfer ownership
     * @param newOwner New owner address
     */
    function transferOwnership(address newOwner) external onlyOwner {
        require(newOwner != address(0), "Invalid address");
        
        address oldOwner = owner;
        owner = newOwner;
        
        emit OwnershipTransferred(oldOwner, newOwner);
    }
    
    /**
     * @notice Check if a nullifier has been used
     * @param nullifier Nullifier to check
     */
    function isNullifierUsed(bytes32 nullifier) external view returns (bool) {
        return usedNullifiers[nullifier];
    }
    
    // ============ Internal Functions ============
    
    /**
     * @notice Internal proof verification using pairing check
     * @param evidenceType Type of evidence
     * @param proof Groth16 proof
     * @param inputs Public inputs
     * @return valid Whether proof is valid
     */
    function _verifyProof(
        EvidenceType evidenceType,
        Proof calldata proof,
        uint256[] memory inputs
    ) internal view returns (bool valid) {
        VerifyingKey storage vk = verifyingKeys[evidenceType];
        
        // Check that vk is set
        if (vk.ic.length == 0) return false;
        
        // Compute linear combination of inputs with IC
        uint256[2] memory vk_x = [uint256(0), uint256(0)];
        
        for (uint256 i = 0; i < inputs.length; i++) {
            // vk_x = vk_x + inputs[i] * vk.ic[i + 1]
            vk_x = _addG1(
                vk_x,
                _scalarMulG1(vk.ic[i + 1], inputs[i])
            );
        }
        
        // Add first IC element
        vk_x = _addG1(vk_x, vk.ic[0]);
        
        // Pairing check: e(A, B) * e(-vk_x, gamma) * e(-vk.alpha, delta) = 1
        // Simplified: just check e(proof.A, proof.B) == e(vk_x, vk.gamma2)
        
        // NOTE: This is a simplified placeholder.
        // In production, use the full pairing check with a library like
        // https://github.com/iden3/snarkjs/blob/master/smart_contracts/verifier_groth16.sol
        
        // For now, return true if vk is set (placeholder)
        return vk.ic.length > 0;
    }
    
    // ============ Helper Functions ============
    
    /// @notice Add two G1 points
    function _addG1(
        uint256[2] memory p1,
        uint256[2] memory p2
    ) internal pure returns (uint256[2] memory) {
        // Placeholder: would use BN128 curve operations
        return [p1[0] + p2[0], p1[1] + p2[1]];
    }
    
    /// @notice Multiply G1 point by scalar
    function _scalarMulG1(
        uint256[2] memory p,
        uint256 s
    ) internal pure returns (uint256[2] memory) {
        // Placeholder: would use BN128 curve operations
        return [p[0] * s, p[1] * s];
    }
    
    // ============ Batch Verification ============
    
    /**
     * @notice Verify multiple proofs in a batch (gas efficient)
     * @param evidenceTypes Types of evidence for each proof
     * @param proofs Array of proofs
     * @param allInputs Array of public inputs for each proof
     * @return results Array of verification results
     */
    function batchVerify(
        EvidenceType[] calldata evidenceTypes,
        Proof[] calldata proofs,
        uint256[][] calldata allInputs
    ) external view returns (bool[] memory results) {
        require(
            evidenceTypes.length == proofs.length && 
            proofs.length == allInputs.length,
            "Length mismatch"
        );
        
        results = new bool[](proofs.length);
        
        for (uint256 i = 0; i < proofs.length; i++) {
            // Check nullifier not used
            bytes32 nullifier = keccak256(abi.encodePacked(allInputs[i]));
            if (usedNullifiers[nullifier]) {
                results[i] = false;
                continue;
            }
            
            // Verify proof
            results[i] = _verifyProof(
                evidenceTypes[i],
                proofs[i],
                allInputs[i]
            );
        }
        
        return results;
    }
}
