# Deploy Prometheus + Alertmanager on the edge VM and scrape validator fleet /metrics.
#
# Generates testnet/monitoring/prometheus-gcp.yml from the validator fleet internal IP,
# syncs the repo to the edge VM, and starts docker compose.
#
# Usage:
#   .\testnet\gcp\deploy-monitoring.ps1
#   .\testnet\gcp\deploy-monitoring.ps1 -SkipSync
#   .\testnet\gcp\deploy-monitoring.ps1 -ValidatorInternalIp 10.128.0.5

param(
    [string]$ProjectId = "",
    [string]$Zone = "",
    [string]$VmName = "",
    [string]$ValidatorInternalIp = "",
    [switch]$SkipSync
)

$ErrorActionPreference = "Stop"
$gcpDir = Split-Path -Parent $MyInvocation.MyCommand.Path
$testnetDir = Split-Path -Parent $gcpDir
$repoRoot = Split-Path -Parent $testnetDir
$monitoringDir = Join-Path $testnetDir "monitoring"
$cfg = & (Join-Path $gcpDir "_Load-HostingEnv.ps1")

function Escape-YamlSingleQuoted([string]$Value) {
    if (-not $Value) { return "" }
    return ($Value -replace "'", "''")
}

function Write-AlertmanagerGcpConfig {
    param(
        [string]$OutPath,
        [string]$SlackWebhookUrl = "",
        [string]$PagerDutyRoutingKey = "",
        [string]$NtfyTopic = "",
        [string]$NtfyServer = "https://ntfy.sh",
        [string]$WebhookUrl = "",
        [string]$EmailTo = "",
        [string]$SmtpHost = "",
        [string]$SmtpUser = "",
        [string]$SmtpPassword = ""
    )

    function Receiver-Integrations {
        param(
            [bool]$IncludePagerDuty = $false
        )
        $parts = @()
        if ($SlackWebhookUrl) {
            $url = Escape-YamlSingleQuoted $SlackWebhookUrl
            $parts += @"
    slack_configs:
      - api_url: '$url'
        send_resolved: true
        title: '{{ .CommonAnnotations.summary }}'
        text: '{{ .CommonAnnotations.description }}'
"@
        }
        if ($IncludePagerDuty -and $PagerDutyRoutingKey) {
            $key = Escape-YamlSingleQuoted $PagerDutyRoutingKey
            $parts += @"

    pagerduty_configs:
      - routing_key: '$key'
        send_resolved: true
"@
        }
        if ($NtfyTopic) {
            $topic = Escape-YamlSingleQuoted $NtfyTopic.Trim().TrimStart('/')
            $server = ($NtfyServer -replace '/$', '').Trim()
            $ntfyUrl = Escape-YamlSingleQuoted "$server/$topic"
            $parts += @"

    webhook_configs:
      - url: '$ntfyUrl'
        send_resolved: true
"@
        } elseif ($WebhookUrl) {
            $url = Escape-YamlSingleQuoted $WebhookUrl
            $parts += @"

    webhook_configs:
      - url: '$url'
        send_resolved: true
"@
        }
        if ($EmailTo -and $SmtpHost -and $SmtpUser -and $SmtpPassword) {
            $to = Escape-YamlSingleQuoted $EmailTo
            $from = Escape-YamlSingleQuoted $SmtpUser
            $smtpHost = Escape-YamlSingleQuoted $SmtpHost
            $user = Escape-YamlSingleQuoted $SmtpUser
            $pass = Escape-YamlSingleQuoted $SmtpPassword
            $parts += @"

    email_configs:
      - to: '$to'
        from: '$from'
        smarthost: '$smtpHost'
        auth_username: '$user'
        auth_password: '$pass'
        require_tls: true
        send_resolved: true
"@
        }
        return ($parts -join "")
    }

    $defaultIntegrations = Receiver-Integrations -IncludePagerDuty $false
    $criticalIntegrations = Receiver-Integrations -IncludePagerDuty $true
    $warningIntegrations = Receiver-Integrations -IncludePagerDuty $false

    $defaultReceiver = "  - name: default$defaultIntegrations"
    $criticalReceiver = "  - name: critical$criticalIntegrations"
    $warningReceiver = "  - name: warning$warningIntegrations"

    $body = @"
# Generated by deploy-monitoring.ps1 - do not edit by hand.
global:
  resolve_timeout: 5m

route:
  group_by: [alertname, instance]
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 4h
  receiver: default

  routes:
    - match:
        severity: critical
      receiver: critical
      repeat_interval: 30m
    - match:
        severity: warning
      receiver: warning

receivers:
$defaultReceiver

$criticalReceiver

$warningReceiver

inhibit_rules:
  - source_match:
      alertname: CregNodeDown
    target_match:
      alertname: CregBlockProductionStalled
    equal: [instance]
"@
    [System.IO.File]::WriteAllText($OutPath, $body)
}

function Log($m) { Write-Host "[deploy-monitoring] $m" }

if (-not $ProjectId) { $ProjectId = $cfg.GCP_PROJECT }
if (-not $Zone) { $Zone = $cfg.GCP_ZONE }
if (-not $VmName) { $VmName = $cfg.GCP_VM_NAME }

$envFile = Join-Path $testnetDir "sepolia-3node.env"
$fleetMode = $true
if (Test-Path $envFile) {
    $fleetMode = Select-String -Path $envFile -Pattern '^\s*CREG_VALIDATOR_FLEET_MODE\s*=\s*true' -Quiet
}

if (-not $ValidatorInternalIp) {
    if (Test-Path $envFile) {
        foreach ($line in Get-Content $envFile) {
            if ($line -match '^\s*CREG_VALIDATOR_VM_INTERNAL_IP\s*=\s*(\S+)') {
                $ValidatorInternalIp = $matches[1].Trim()
                break
            }
        }
    }
    if (-not $ValidatorInternalIp) {
        $ipLine = & (Join-Path $gcpDir "get-validator-fleet-internal-ip.ps1") | Where-Object { $_ -match '^CREG_VALIDATOR_VM_INTERNAL_IP=' }
        if ($ipLine) {
            $ValidatorInternalIp = ($ipLine -split '=', 2)[1].Trim()
        }
    }
}

if ($fleetMode -and -not $ValidatorInternalIp) {
    throw "Validator fleet internal IP unknown. Set CREG_VALIDATOR_VM_INTERNAL_IP in sepolia-3node.env or pass -ValidatorInternalIp."
}

$targets = @()
if ($fleetMode) {
    $targets = @(
        "${ValidatorInternalIp}:28180",
        "${ValidatorInternalIp}:28181",
        "${ValidatorInternalIp}:28182"
    )
    Log "Fleet mode: scraping validator VM $ValidatorInternalIp (28180-28182)"
} else {
    $targets = @("127.0.0.1:28180", "127.0.0.1:28181", "127.0.0.1:28182")
    Log "Co-located stack mode: scraping localhost 28180-28182"
}

$targetYaml = ($targets | ForEach-Object { "          - `"$_`"" }) -join "`n"
$prometheusPath = Join-Path $monitoringDir "prometheus-gcp.yml"
$prometheusBody = @"
global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: creg-testnet-gcp
    environment: public-alpha

alerting:
  alertmanagers:
    - static_configs:
        - targets: ["alertmanager:9093"]

rule_files:
  - "alerts.yml"

scrape_configs:
  - job_name: creg-node
    static_configs:
      - targets:
$targetYaml
        labels:
          role: validator-fleet
    metrics_path: /metrics
    scrape_interval: 15s
    scrape_timeout: 10s

  - job_name: prometheus
    static_configs:
      - targets: ["localhost:9090"]
"@
[System.IO.File]::WriteAllText($prometheusPath, $prometheusBody)
Log "Wrote $prometheusPath"

$slackUrl = $cfg.GCP_ALERT_SLACK_WEBHOOK_URL
$pagerKey = $cfg.GCP_ALERT_PAGERDUTY_ROUTING_KEY
$ntfyTopic = $cfg.GCP_ALERT_NTFY_TOPIC
$ntfyServer = if ($cfg.GCP_ALERT_NTFY_SERVER) { $cfg.GCP_ALERT_NTFY_SERVER } else { "https://ntfy.sh" }
$webhookUrl = $cfg.GCP_ALERT_WEBHOOK_URL
$emailTo = if ($cfg.GCP_ALERT_EMAIL_TO) { $cfg.GCP_ALERT_EMAIL_TO } else { $cfg.GCP_BUDGET_ALERT_EMAIL }
$alertmanagerPath = Join-Path $monitoringDir "alertmanager-gcp.yml"
Write-AlertmanagerGcpConfig `
    -OutPath $alertmanagerPath `
    -SlackWebhookUrl $slackUrl `
    -PagerDutyRoutingKey $pagerKey `
    -NtfyTopic $ntfyTopic `
    -NtfyServer $ntfyServer `
    -WebhookUrl $webhookUrl `
    -EmailTo $emailTo `
    -SmtpHost $cfg.GCP_ALERT_SMTP_HOST `
    -SmtpUser $cfg.GCP_ALERT_SMTP_USER `
    -SmtpPassword $cfg.GCP_ALERT_SMTP_PASSWORD
if ($slackUrl) {
    Log "Wrote $alertmanagerPath (Slack configured)"
} elseif ($ntfyTopic) {
    Log "Wrote $alertmanagerPath (ntfy topic: $ntfyTopic)"
} elseif ($webhookUrl) {
    Log "Wrote $alertmanagerPath (generic webhook configured)"
} elseif ($emailTo -and $cfg.GCP_ALERT_SMTP_HOST -and $cfg.GCP_ALERT_SMTP_USER -and $cfg.GCP_ALERT_SMTP_PASSWORD) {
    Log "Wrote $alertmanagerPath (email to $emailTo)"
} elseif ($pagerKey) {
    Log "Wrote $alertmanagerPath (PagerDuty only)"
} else {
    Log "Wrote $alertmanagerPath (no external receivers - run setup-alert-receiver.ps1)"
}

if (-not $SkipSync) {
    Log "Syncing repo to edge VM $VmName..."
    & (Join-Path $gcpDir "sync-local-repo.ps1") -ProjectId $ProjectId -Zone $Zone -VmName $VmName
} else {
    Log "Skipping full repo sync (-SkipSync); uploading monitoring config only."
    $repoSlug = ($cfg.GITHUB_REPO -split '/')[-1]
    $sshOpts = @("--zone=$Zone", "--project=$ProjectId", "--tunnel-through-iap", "--strict-host-key-checking=no", "--quiet")
    $remoteHome = (gcloud compute ssh $VmName @sshOpts --command="printf '%s' `$HOME").Trim()
    $remoteMonitoring = "$remoteHome/creg-hosting/$repoSlug/chain-registry/testnet/monitoring"
    gcloud compute ssh $VmName @sshOpts --command="mkdir -p '$remoteMonitoring'" | Out-Null
    foreach ($f in @("prometheus-gcp.yml", "creg-alerts.yml", "alertmanager-gcp.yml", "docker-compose.monitoring.yml")) {
        $local = Join-Path $monitoringDir $f
        if (-not (Test-Path $local)) { throw "Missing $local" }
        gcloud compute scp $local "${VmName}:${remoteMonitoring}/$f" @sshOpts
    }
}

$repoSlug = ($cfg.GITHUB_REPO -split '/')[-1]
$remoteComposeDir = "`$HOME/creg-hosting/$repoSlug/chain-registry/testnet/monitoring"
$remoteCmd = @"
set -euo pipefail
cd $remoteComposeDir
DOCKER=(docker)
if ! docker info >/dev/null 2>&1; then
  if sudo docker info >/dev/null 2>&1; then
    DOCKER=(sudo docker)
  else
    echo 'Docker not available on edge VM' >&2
    exit 1
  fi
fi
`${DOCKER[@]} compose -f docker-compose.monitoring.yml pull
`${DOCKER[@]} compose -f docker-compose.monitoring.yml up -d --force-recreate alertmanager prometheus
`${DOCKER[@]} compose -f docker-compose.monitoring.yml ps
"@

Log "Starting monitoring stack on $VmName..."
& (Join-Path $gcpDir "ssh-vm.ps1") -Command $remoteCmd
if ($LASTEXITCODE -ne 0) { throw "remote monitoring start failed" }

Log "Done. Verify:"
Log "  .\testnet\gcp\verify-monitoring.ps1"
Log "  .\testnet\gcp\ssh-vm.ps1 -Command 'curl -fsS http://127.0.0.1:9090/-/healthy'"
